#!/usr/bin/env bash
# Generate N Phase 1 controller services for the local stack (operations §2).
#
# Produces, under deploy/:
#   docker-compose.override.yml  — one named controller service per greenhouse
#   controllers/<id>.toml        — each controller's config (broker, REST bind, unique id+seed)
#   controllers/register.sh      — registers each greenhouse with the platform API after `up`
#
# Each controller is a distinct identity (its own controller_id + simulation seed), which is
# why named services with per-service config mounts are used instead of `--scale`.
#
# Usage:  bash deploy/scripts/gen-controllers.sh [N]   (default N=2)
set -euo pipefail

N="${1:-2}"
if ! [[ "$N" =~ ^[0-9]+$ ]] || (( N < 1 )); then
  echo "usage: gen-controllers.sh N   (N must be an integer >= 1)" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "$SCRIPT_DIR")"
REPO_DIR="$(dirname "$DEPLOY_DIR")"
TEMPLATE="$REPO_DIR/climate-controller/config/greenhouse.example.toml"
OUT_DIR="$DEPLOY_DIR/controllers"
OVERRIDE="$DEPLOY_DIR/docker-compose.override.yml"
REGISTER="$OUT_DIR/register.sh"

[[ -f "$TEMPLATE" ]] || { echo "template not found: $TEMPLATE" >&2; exit 1; }
mkdir -p "$OUT_DIR"

letters=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
id_for() {
  local i="$1"
  if (( i < 26 )); then echo "gh-${letters[$i]}"; else echo "gh-$((i + 1))"; fi
}

{
  echo "# GENERATED by scripts/gen-controllers.sh — do not edit by hand."
  echo "# $N Phase 1 controller service(s); merged over docker-compose.yml."
  echo "name: greenhouse"
  echo "services:"
} > "$OVERRIDE"

{
  echo "#!/usr/bin/env bash"
  echo "# GENERATED by gen-controllers.sh — registers each greenhouse with the platform API."
  echo "set -euo pipefail"
  echo 'API="${API_URL:-http://localhost:8080}"'
  echo 'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"'
  echo '# Registration is an operator write; fetch a token (non-fatal, so this still works against an'
  echo '# unauthenticated api).'
  echo 'TOKEN="$(bash "$SCRIPT_DIR/../scripts/get-token.sh" 2>/dev/null || true)"'
  echo 'AUTH=(); [[ -n "$TOKEN" ]] && AUTH=(-H "Authorization: Bearer $TOKEN")'
} > "$REGISTER"

for (( i = 0; i < N; i++ )); do
  id="$(id_for "$i")"
  toml="$OUT_DIR/$id.toml"
  seed=$(( 6582955728036744000 + i ))

  sed -e "s|^controller_id = .*|controller_id = \"$id\"|" \
      -e "s|^broker_url = .*|broker_url = \"mqtt://mqtt:1883\"|" \
      -e "s|^bind_addr = .*|bind_addr = \"0.0.0.0:8080\"|" \
      -e "s|^seed = .*|seed = $seed|" \
      "$TEMPLATE" > "$toml"

  cat >> "$OVERRIDE" <<EOF
  $id:
    build:
      context: ../climate-controller
    image: greenhouse-controller:latest
    container_name: greenhouse-$id
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_healthy
    command: ["/config/greenhouse.toml"]
    volumes:
      - ./controllers/$id.toml:/config/greenhouse.toml:ro
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M
EOF

  printf 'curl -fsS -X POST "$API/api/greenhouses" "${AUTH[@]}" -H '\''Content-Type: application/json'\'' -d '\''{"id":"%s","display_name":"Greenhouse %s","crop":null,"controller":{"rest_base_url":"http://%s:8080","mqtt_topic_root":"gh/%s"}}'\'' && echo " registered %s"\n' \
    "$id" "${id#gh-}" "$id" "$id" "$id" >> "$REGISTER"
done

chmod +x "$REGISTER" 2>/dev/null || true

echo "Generated $N controller service(s):"
echo "  override : $OVERRIDE"
echo "  configs  : $OUT_DIR/<id>.toml"
echo "  register : $REGISTER"
echo
echo "Next:"
echo "  docker compose --env-file deploy/.env -f deploy/docker-compose.yml -f deploy/docker-compose.override.yml up -d --build"
echo "  bash $REGISTER"
