#!/usr/bin/env bash
# Generate N Phase 1 controller services for the local stack (operations §2).
#
# Produces, under deploy/:
#   docker-compose.override.yml  — one named controller service per greenhouse
#   controllers/<id>.toml        — each controller's config (broker, REST bind, unique id+seed)
#   controllers/register.sh      — registers each greenhouse with the platform API after `up`
#
# Each controller is a distinct identity (its own controller_id + simulation seed), which is
# why named services with per-service config mounts are used instead of `--scale`.
#
# Usage:  bash deploy/scripts/gen-controllers.sh [N]   (default N=2)
set -euo pipefail

N="${1:-2}"
if ! [[ "$N" =~ ^[0-9]+$ ]] || (( N < 1 )); then
  echo "usage: gen-controllers.sh N   (N must be an integer >= 1)" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "$SCRIPT_DIR")"
REPO_DIR="$(dirname "$DEPLOY_DIR")"
TEMPLATE="$REPO_DIR/climate-controller/config/greenhouse.example.toml"
OUT_DIR="$DEPLOY_DIR/controllers"
OVERRIDE="$DEPLOY_DIR/docker-compose.override.yml"
REGISTER="$OUT_DIR/register.sh"
# Prometheus file-based service discovery: the controllers' /metrics targets (operations §1). The
# prometheus service watches this dir, so regenerating the fleet re-points scraping with no restart.
TARGETS_DIR="$DEPLOY_DIR/prometheus/targets"
TARGETS_FILE="$TARGETS_DIR/controllers.json"

[[ -f "$TEMPLATE" ]] || { echo "template not found: $TEMPLATE" >&2; exit 1; }
mkdir -p "$OUT_DIR" "$TARGETS_DIR"

# Optional per-controller pre-shared bearer token (RFC-011, dormant by default). Set
# CONTROLLER_AUTH_TOKENS=1 to mint a random token per controller: the controller then requires it on
# its REST write endpoints and the greenhouse is registered with the matching token so the platform
# presents it downward. Unset (default) → controllers stay unauthenticated, as today.
MINT_TOKENS="${CONTROLLER_AUTH_TOKENS:-0}"
mint_token() { LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c 32; }

letters=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
id_for() {
  local i="$1"
  if (( i < 26 )); then echo "gh-${letters[$i]}"; else echo "gh-$((i + 1))"; fi
}

{
  echo "# GENERATED by scripts/gen-controllers.sh — do not edit by hand."
  echo "# $N Phase 1 controller service(s); merged over docker-compose.yml."
  echo "name: greenhouse"
  echo "services:"
} > "$OVERRIDE"

{
  echo "#!/usr/bin/env bash"
  echo "# GENERATED by gen-controllers.sh — registers each greenhouse with the platform API."
  echo "set -euo pipefail"
  echo 'API="${API_URL:-http://localhost:8080}"'
  echo 'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"'
  echo '# Registration is an operator write; fetch a token (non-fatal, so this still works against an'
  echo '# unauthenticated api).'
  echo 'TOKEN="$(bash "$SCRIPT_DIR/../scripts/get-token.sh" 2>/dev/null || true)"'
  echo 'AUTH=(); [[ -n "$TOKEN" ]] && AUTH=(-H "Authorization: Bearer $TOKEN")'
} > "$REGISTER"

targets_json=""
for (( i = 0; i < N; i++ )); do
  id="$(id_for "$i")"
  toml="$OUT_DIR/$id.toml"
  seed=$(( 6582955728036744000 + i ))
  # Each controller's REST server (and thus /metrics) is internal at <id>:8080; add it to the
  # Prometheus file-SD target list. greenhouse_id is a metric const label, so it's not set here.
  targets_json+="${targets_json:+, }\"$id:8080\""

  # When minting, uncomment the template's auth_token and echo the same token into the registration
  # body so the controller and the platform share it. Off by default → both stay untokened.
  auth_sed=()
  bearer_json=""
  if [[ "$MINT_TOKENS" == "1" ]]; then
    token="$(mint_token)"
    auth_sed=(-e "s|^# auth_token = .*|auth_token = \"$token\"|")
    bearer_json=",\"bearer_token\":\"$token\""
  fi

  sed -e "s|^controller_id = .*|controller_id = \"$id\"|" \
      -e "s|^broker_url = .*|broker_url = \"mqtt://mqtt:1883\"|" \
      -e "s|^bind_addr = .*|bind_addr = \"0.0.0.0:8080\"|" \
      -e "s|^seed = .*|seed = $seed|" \
      "${auth_sed[@]}" \
      "$TEMPLATE" > "$toml"

  cat >> "$OVERRIDE" <<EOF
  $id:
    build:
      context: ../climate-controller
    image: greenhouse-controller:latest
    container_name: greenhouse-$id
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_healthy
    command: ["/config/greenhouse.toml"]
    volumes:
      - ./controllers/$id.toml:/config/greenhouse.toml:ro
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M
EOF

  printf 'curl -fsS -X POST "$API/api/greenhouses" "${AUTH[@]}" -H '\''Content-Type: application/json'\'' -d '\''{"id":"%s","display_name":"Greenhouse %s","crop":null,"controller":{"rest_base_url":"http://%s:8080","mqtt_topic_root":"gh/%s"%s}}'\'' && echo " registered %s"\n' \
    "$id" "${id#gh-}" "$id" "$id" "$bearer_json" "$id" >> "$REGISTER"
done

# Prometheus file-SD: one target group for the whole controller fleet (operations §1).
cat > "$TARGETS_FILE" <<EOF
[
  {
    "labels": { "job": "controllers" },
    "targets": [$targets_json]
  }
]
EOF

chmod +x "$REGISTER" 2>/dev/null || true

echo "Generated $N controller service(s):"
echo "  override : $OVERRIDE"
echo "  configs  : $OUT_DIR/<id>.toml"
echo "  register : $REGISTER"
echo "  scrape   : $TARGETS_FILE"
echo
echo "Next:"
echo "  docker compose --env-file deploy/.env -f deploy/docker-compose.yml -f deploy/docker-compose.override.yml up -d --build"
echo "  bash $REGISTER"
