"""Domain models mirroring the optimizer's wire contracts (Pydantic v2)."""

from __future__ import annotations

from .context import (
    ActuatorSnapshot,
    Bound,
    CurrentSetpoints,
    DataQuality,
    MetricFreshness,
    MetricSummarySeries,
    PlanningContext,
    SensorFault,
    StageBounds,
    SummaryBucket,
    ZoneBounds,
)
from .enums import (
    REASON_CLASS,
    ActuatorHealth,
    ActuatorName,
    BackendRole,
    ControllerMode,
    Interval,
    Metric,
    OutcomeStatus,
    Provider,
    ReasonClass,
    ReasonCode,
    SensorFaultKind,
    SetpointSource,
)
from .plan import (
    Backend,
    EscalationHint,
    Horizon,
    ObjectiveScores,
    OptimizerPlan,
    Outcome,
    PlanRecord,
    TrajectoryPoint,
)
from .setpoints import Setpoints, SetpointsPatch, ZoneTargets

__all__ = [
    "REASON_CLASS",
    "ActuatorHealth",
    "ActuatorName",
    "ActuatorSnapshot",
    "Backend",
    "BackendRole",
    "Bound",
    "ControllerMode",
    "CurrentSetpoints",
    "DataQuality",
    "EscalationHint",
    "Horizon",
    "Interval",
    "Metric",
    "MetricFreshness",
    "MetricSummarySeries",
    "ObjectiveScores",
    "OptimizerPlan",
    "Outcome",
    "OutcomeStatus",
    "PlanRecord",
    "PlanningContext",
    "Provider",
    "ReasonClass",
    "ReasonCode",
    "SensorFault",
    "SensorFaultKind",
    "Setpoints",
    "SetpointSource",
    "SetpointsPatch",
    "StageBounds",
    "SummaryBucket",
    "TrajectoryPoint",
    "ZoneBounds",
    "ZoneTargets",
]
